# Generated by Django 5.1 on 2026-03-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Island",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("wp_category_id", models.IntegerField(blank=True, null=True)),
                (
                    "island_page_title",
                    models.CharField(default="Page Title", max_length=80),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                (
                    "company_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        null=True,
                    ),
                ),
                (
                    "company_reviews",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("details", models.TextField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=10)),
                ("price", models.IntegerField(default=0)),
                ("is_promo", models.BooleanField(default=False)),
                ("promo_amount", models.IntegerField(default=0)),
                ("promo_code", models.CharField(blank=True, max_length=100)),
                ("is_public", models.BooleanField(default=False)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("fh_id", models.IntegerField(blank=True, null=True)),
                ("referral_link", models.URLField(blank=True)),
                ("image_URL", models.URLField(blank=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(related_name="bookings", to="core.category"),
                ),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.island"
                    ),
                ),
            ],
        ),
    ]
