# Generated by Django 5.2.12 on 2026-03-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
