# Generated by Django 5.2.12 on 2026-03-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="company_rating",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
