# Generated by Django 5.2.12 on 2026-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_booking_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="duration",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
