# Generated by Django 5.2.12 on 2026-03-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_booking_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="promo_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
