# Generated by Django 5.2.12 on 2026-03-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_booking_promo_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="island",
            name="slug",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
