# Generated by Django 5.2.12 on 2026-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_island_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="promo_amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
