# Generated by Django 5.2.12 on 2026-03-22 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_booking_price_alter_booking_promo_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="company_rating",
        ),
    ]
