# Generated by Django 5.2.12 on 2026-03-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_booking_company_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="company_rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
